const type = {
    SET_COURSE: 'SET_COURSE',
    ADD_COURSE: 'ADD_COURSE',
    ADD_WEEK: 'ADD_WEEK',
    DELETE_WEEK: 'DELETE_WEEK',
    ADD_LECTURE: 'ADD_LECTURE',
    DELETE_LECTURE: 'DELETE_LECTURE',
};

export default type;
